name: Rust CI

on:
  push:
    branches:
      - master
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        target: thumbv6m-none-eabi

    - name: Build for RP2040
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target thumbv6m-none-eabi

    # Solo ejecuta la publicación si estamos en la rama master
    - name: Publish to crates.io
      if: github.ref == 'refs/heads/master'
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --token ${{ secrets.CARGO_TOKEN }}
